// ─── Topic-based text generation for TypeTunes ────────────────────────────────

export interface Topic {
  id: string;
  label: string;
  emoji: string;
  paragraphs: string[];
}

// ─── 20 Preset Topics ─────────────────────────────────────────────────────────

export const PRESET_TOPICS: Topic[] = [
  {
    id: 'technology',
    label: 'Technology',
    emoji: '💻',
    paragraphs: [
      'Software engineers spend most of their day reading code rather than writing it. Understanding what code does, why it was written that way, and how it connects to everything else requires deep attention and patience. The best programmers are not those who type the fastest but those who think the most clearly before touching the keyboard.',
      'Artificial intelligence is reshaping every industry, from healthcare diagnostics to supply chain management. Machine learning models trained on vast datasets can now recognise patterns that no human expert would notice in a lifetime of study. The challenge is not building the models but asking the right questions and interpreting the answers responsibly.',
      'Open source software powers the modern internet. Web servers, programming languages, databases, and operating systems that run billions of devices are maintained by volunteer communities and corporate contributors working together. The economic value generated by open source dwarfs the cost of maintaining it, yet most of that value flows to companies rather than to the contributors.',
    ],
  },
  {
    id: 'science',
    label: 'Science',
    emoji: '🔬',
    paragraphs: [
      'Scientific progress does not move in a straight line. Most experiments fail, most hypotheses are wrong, and most papers go unread. The papers that do matter often contradict what came before. Science advances through a messy, self-correcting process that looks nothing like the clean narratives in textbooks but produces knowledge that is more reliable than any other method humans have devised.',
      'The human brain contains roughly eighty-six billion neurons, each connected to thousands of others. The total number of synaptic connections exceeds the number of stars in the observable universe. We have mapped the physical structure of the brain in extraordinary detail, yet we still cannot explain how this network of electrical signals gives rise to consciousness, creativity, or the experience of colour.',
      'Physics at the quantum scale behaves nothing like the everyday world we experience. Particles exist in superpositions of multiple states until observed. Objects can be entangled across vast distances, so that measuring one instantly affects the other. These phenomena are not theoretical curiosities but the foundations of transistors, lasers, and the technology that makes modern computers possible.',
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    emoji: '🌿',
    paragraphs: [
      'A single teaspoon of healthy forest soil contains more living organisms than there are people on Earth. Fungi, bacteria, nematodes, and arthropods form intricate networks that cycle nutrients, break down dead matter, and protect plant roots from disease. When we clear a forest, we do not just remove the trees but collapse an entire underground civilisation that took centuries to build.',
      'Migration is one of nature\'s most astonishing achievements. Arctic terns travel from pole to pole every year, covering seventy thousand kilometres in a single migration cycle. Monarch butterflies navigate from Canada to a specific forest in Mexico using a solar compass and magnetic field sensors that scientists are still working to understand fully. These journeys happen without maps, without guides, on inherited instinct alone.',
      'Coral reefs cover less than one percent of the ocean floor yet support nearly a quarter of all marine species. They are among the oldest and most complex ecosystems on the planet, built grain by grain over thousands of years by the tiny polyps that secrete their calcium carbonate skeletons. Rising ocean temperatures cause bleaching events that can kill an entire reef system in a matter of weeks.',
    ],
  },
  {
    id: 'history',
    label: 'History',
    emoji: '📜',
    paragraphs: [
      'The printing press did not simply make books cheaper. It changed who could read, who could write, and who could be believed. Within fifty years of Gutenberg\'s invention, thousands of titles were in circulation across Europe. Ideas that the church had controlled for centuries could now spread faster than any authority could suppress them. The Reformation, the Scientific Revolution, and the Enlightenment all followed in the centuries after.',
      'Empires rarely fall from external pressure alone. The Western Roman Empire\'s collapse involved centuries of fiscal crisis, military overextension, political instability, and the gradual erosion of civic identity that made Romans willing to defend their civilisation. The barbarian invasions were as much a symptom as a cause. The lesson historians return to repeatedly is that institutions decay slowly until they collapse quickly.',
      'The Industrial Revolution transformed not just economies but human biology. For the first time in history, a significant portion of the population moved from rural subsistence farming to urban wage labour within a single generation. Life expectancy initially fell in industrial cities before rising dramatically once sanitation and nutrition improved. The disruption we associate with modern technology is not unprecedented but it is accelerating.',
    ],
  },
  {
    id: 'space',
    label: 'Space',
    emoji: '🚀',
    paragraphs: [
      'The observable universe is roughly forty-six billion light years in radius, containing at least two trillion galaxies. Each galaxy contains hundreds of billions of stars, and around most of those stars orbit planets. The number of potentially habitable worlds in the observable universe alone is greater than all the grains of sand on every beach on Earth. The silence in our radio telescopes remains one of the most profound mysteries in science.',
      'A black hole is a region of space where gravity is so strong that not even light can escape once it crosses the event horizon. They are not cosmic vacuum cleaners but simply regions of concentrated mass. Stars, planets, and gas clouds orbit supermassive black holes at the centres of most large galaxies, including the four-million-solar-mass black hole at the centre of our own Milky Way.',
      'The Moon formed approximately four and a half billion years ago when a Mars-sized object called Theia collided with the young Earth. The impact ejected an enormous cloud of debris that coalesced into the satellite we see today. The Moon stabilises Earth\'s axial tilt, which regulates our seasons. Without it, Earth\'s climate would be dramatically more chaotic, and complex life might never have evolved.',
    ],
  },
  {
    id: 'health',
    label: 'Health',
    emoji: '🏃',
    paragraphs: [
      'Exercise is the most evidence-backed intervention for mental health that medicine has ever studied. Regular aerobic activity reduces symptoms of depression as effectively as antidepressant medication for mild to moderate cases, without side effects and with benefits that compound over time. The mechanism involves neuroplasticity, inflammation reduction, and the release of growth factors that literally build new brain tissue.',
      'Sleep is not passive rest but an active biological process during which the brain flushes metabolic waste products, consolidates memories, repairs cellular damage, and regulates hormones. Chronic sleep deprivation impairs cognitive performance as severely as legal intoxication and is associated with increased risk of cardiovascular disease, type two diabetes, and cognitive decline in later life.',
      'The gut contains approximately one hundred trillion microorganisms, collectively weighing about two kilograms. This microbiome influences immune function, inflammation, nutrient absorption, and even mood and behaviour through the gut-brain axis. Diet, antibiotics, and early childhood environment all shape the microbiome in ways that have lasting health consequences, making it one of the most active areas of medical research today.',
    ],
  },
  {
    id: 'psychology',
    label: 'Psychology',
    emoji: '🧠',
    paragraphs: [
      'Procrastination is not a time management problem. It is an emotional regulation problem. People avoid tasks not because they do not care about them but because those tasks trigger anxiety, self-doubt, boredom, or resentment. The task feels threatening, so the mind generates diversions. Understanding this reframes the solution: rather than scheduling better, you need to reduce the emotional charge attached to the task itself.',
      'The most effective learning technique, according to decades of cognitive science research, is retrieval practice. Testing yourself on material you have studied produces far better retention than re-reading or highlighting. The act of trying to recall something, and succeeding or failing, strengthens the neural pathways associated with that memory in ways that passive review cannot match.',
      'Confirmation bias is one of the most powerful and pervasive cognitive distortions. Once we hold a belief, we unconsciously seek out information that confirms it and discount or ignore information that contradicts it. This is not a failure of intelligence but a fundamental feature of how the human mind processes information efficiently. The most rigorous thinkers are those who have learned to actively seek disconfirming evidence.',
    ],
  },
  {
    id: 'philosophy',
    label: 'Philosophy',
    emoji: '🤔',
    paragraphs: [
      'The ancient question of what constitutes a good life has generated thousands of years of philosophical debate without a settled answer. Aristotle argued for eudaimonia, flourishing through virtuous activity over a lifetime. The Epicureans championed tranquility and freedom from unnecessary desire. The Stoics emphasised alignment with reason and acceptance of what is beyond our control. Each tradition captures something true that the others miss.',
      'Free will is one of philosophy\'s most persistent and practically consequential questions. If our choices are entirely determined by prior causes, including our genetics and environment, then the concept of moral responsibility becomes difficult to defend. But if our choices are random rather than determined, they are not meaningfully ours either. Compatibilist philosophers argue that free will is compatible with determinism when properly understood.',
      'The problem of consciousness, sometimes called the hard problem, asks why there is subjective experience at all. We can explain, in principle, every functional aspect of the brain in physical terms. But why does processing information feel like something from the inside? Why is there an experience of red rather than just a wavelength detection? No physical account of brain function seems to answer this question.',
    ],
  },
  {
    id: 'art',
    label: 'Art & Music',
    emoji: '🎨',
    paragraphs: [
      'Music\'s ability to evoke emotion is not purely cultural. Certain musical features, such as slow tempos, low pitches, and minor harmonies, reliably evoke sadness across cultures that have had no musical contact with each other. Other features are culturally specific, learned through exposure. The interaction between these universal and learned responses is what makes music simultaneously accessible to everyone and endlessly varied across the world.',
      'Improvisation in jazz requires holding a complex set of constraints in mind simultaneously: the chord changes, the melody, the band\'s rhythm, the dynamics of the room, and the musical statement you are trying to make. Experienced improvisers describe a state of flow in which conscious deliberation gives way to automatic, intuitive decision-making. The paradox is that this effortless-seeming freedom requires years of rigorous, structured practice.',
      'Great paintings are rarely about what they depict. Vermeer\'s interiors are about light and time. Caravaggio\'s biblical scenes are about human drama and moral ambiguity. Turner\'s seascapes are about the terror and beauty of natural force. The subject is a vehicle for an experience that the painter wants to share with the viewer. The best art changes what you see when you stop looking at the painting.',
    ],
  },
  {
    id: 'food',
    label: 'Food & Nutrition',
    emoji: '🍽️',
    paragraphs: [
      'Fermentation is one of humanity\'s oldest food technologies, predating agriculture itself. Yeast, bacteria, and fungi transform sugars into acids, alcohols, and gases that preserve food, enhance flavour, and in many cases improve nutritional value. Yogurt, cheese, sourdough, kimchi, miso, and vinegar are all fermented products. The microorganisms involved in traditional fermentation processes have been selectively cultivated over thousands of years of human culture.',
      'Ultra-processed foods are not simply unhealthy ingredients combined. They are engineered products designed to override the body\'s satiety signals, delivering precisely calibrated combinations of fat, sugar, and salt that trigger reward pathways while failing to provide the nutrients and fibre that would normally signal fullness. The degree of processing, not just the nutrient content, is increasingly recognised as an independent predictor of health outcomes.',
      'Coffee is one of the most studied dietary compounds in history. The evidence suggests it reduces risk of type two diabetes, Parkinson\'s disease, and several cancers, and improves cognitive performance and physical endurance. The mechanism involves caffeine\'s blocking of adenosine receptors, but also the thousands of other bioactive compounds in roasted coffee that act as antioxidants and anti-inflammatory agents.',
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    emoji: '✈️',
    paragraphs: [
      'Travel changes you not through the exotic experiences you collect but through the sustained discomfort of being a stranger. When your language does not work, your social scripts do not apply, and your assumptions about how things should be done are constantly violated, you are forced to improvise, observe, and learn in ways that comfortable familiarity at home never requires. The best travel is the kind that genuinely challenges you.',
      'Geography shapes culture in ways that are easy to overlook. Civilisations that arose near navigable rivers developed trade economies early. Island nations developed maritime traditions and decentralised political structures. High-altitude communities developed physiological adaptations and agricultural practices suited to thin air and short growing seasons. The landscape people inhabit for generations leaves its mark on their language, religion, food, and character.',
      'The most linguistically diverse places on Earth are not the great urban centres but remote regions where mountains, rivers, and jungles created barriers that allowed small communities to develop entirely distinct languages over millennia. Papua New Guinea alone contains over eight hundred languages, representing a significant fraction of all human linguistic diversity. Each language is a unique cognitive framework for understanding reality.',
    ],
  },
  {
    id: 'business',
    label: 'Business',
    emoji: '📊',
    paragraphs: [
      'Most startups fail not because their product is bad but because they build something nobody wants. The discipline of validating assumptions before building them into products is the core insight of the lean startup methodology. Talking to customers, running small experiments, and being willing to change direction based on evidence rather than conviction is harder than it sounds because founders are emotionally invested in their initial idea.',
      'Deep work, the ability to focus without distraction on cognitively demanding tasks, is becoming both rarer and more valuable simultaneously. Knowledge workers who can produce complex, high-quality output in concentrated sessions outperform those who spread their attention across constant meetings and messages. The challenge is that shallow busyness feels productive while deep work requires tolerance of discomfort and uncertainty.',
      'Feedback is the mechanism by which organisations improve, yet most feedback cultures are broken. Managers give vague, qualified praise to avoid conflict. Employees give upward feedback that is filtered to be acceptable. Peer reviews become exercises in diplomatic non-communication. Organisations that function well build specific practices around direct, kind, and actionable feedback at every level.',
    ],
  },
  {
    id: 'environment',
    label: 'Climate',
    emoji: '🌍',
    paragraphs: [
      'Biodiversity loss is proceeding faster than the climate crisis yet receives a fraction of the attention. We are in the sixth mass extinction event in Earth\'s history, driven primarily by habitat destruction, with climate change, pollution, and invasive species accelerating the losses. Species extinction is not just an aesthetic tragedy but the destruction of ecological services that underpin agriculture, clean water, and human health.',
      'Rewilding large predators into ecosystems where they have been absent can trigger trophic cascades that transform entire landscapes. When wolves were reintroduced to Yellowstone in 1995, their predation and presence changed where elk grazed, which allowed riverbanks to stabilise and vegetation to recover, which changed water flow and created habitat for beavers, fish, and songbirds. The wolf changed the rivers.',
      'The ocean absorbs roughly a quarter of the carbon dioxide emitted by human activity each year. This has slowed the rate of atmospheric warming but at a cost. As carbon dioxide dissolves in seawater, it forms carbonic acid. Ocean acidity has increased by about thirty percent since the industrial revolution, enough to impair the ability of shellfish, corals, and plankton to build their calcium carbonate structures.',
    ],
  },
  {
    id: 'mathematics',
    label: 'Mathematics',
    emoji: '🔢',
    paragraphs: [
      'Prime numbers, divisible only by one and themselves, appear to be distributed randomly along the number line yet follow patterns subtle enough to have occupied mathematicians for two thousand years. The Riemann hypothesis, one of the most important unsolved problems in mathematics, describes the distribution of primes using a complex-valued function whose zeroes all appear to lie on a single line, a pattern with no known proof.',
      'Probability is the branch of mathematics most consistently violated by human intuition. The Monty Hall problem, in which switching doors doubles your probability of winning a car, baffles people with advanced degrees. The birthday problem, in which twenty-three people in a room have a fifty percent chance of sharing a birthday, seems impossible until you work through the mathematics. Our gut sense of chance is calibrated for a world far simpler than reality.',
      'The Fibonacci sequence, in which each number is the sum of the two preceding it, appears throughout nature in the arrangement of sunflower seeds, pine cone spirals, leaf phyllotaxis, and nautilus shell growth. The reason is not mystical but mechanical: the Fibonacci growth pattern emerges from simple local rules about how to pack objects most efficiently. Nature optimises, and optimal packing in circular growth produces Fibonacci patterns.',
    ],
  },
  {
    id: 'literature',
    label: 'Literature',
    emoji: '📚',
    paragraphs: [
      'Reading fiction builds cognitive empathy in ways that non-fiction does not. When you inhabit a character\'s perspective across hundreds of pages, you practise the mental simulation of experiences and emotions that are not your own. Research consistently finds that people who read literary fiction score higher on measures of theory of mind, the ability to understand that other people have different beliefs, desires, and perspectives.',
      'The short story is the most technically demanding form in fiction. A novel can afford to be slow, to explore digressions, to develop slowly. A short story must achieve its effect within a handful of pages, which means every sentence must carry weight and every word choice matters more than in any other form. The best short stories, by Chekhov, Carver, or Alice Munro, leave you feeling that the story continues beyond its final line.',
      'Languages do not just describe the world; they shape how their speakers perceive it. Languages with many terms for colour distinctions make those distinctions easier to perceive. Languages with different spatial reference systems, absolute versus relative directions, correlate with differences in spatial navigation ability. The Sapir-Whorf hypothesis, that language determines thought, is too strong, but the softer version, that language influences thought, has substantial support.',
    ],
  },
  {
    id: 'sports',
    label: 'Sports',
    emoji: '⚽',
    paragraphs: [
      'Elite athletes in pressure situations do not simply suppress anxiety. They transform it. The physiological arousal that causes amateur athletes to tighten up and make errors is the same arousal that, when reappraised as excitement rather than threat, improves performance. The mental skill of reappraisal, of saying "I am excited" rather than "I am nervous," is trainable and measurable in performance outcomes.',
      'Recovery is not the absence of training but an active biological process. During exercise, muscles sustain microscopic damage. During recovery, they rebuild stronger. The adaptation that produces fitness happens during rest, not during the workout itself. Athletes who chronically underestimate recovery needs plateau or get injured. The optimal training programme is the one that maximises stimulus while minimising accumulated fatigue.',
      'Technique matters more than strength at almost every level of athletic competition. A swimmer with perfect technique and moderate power will outperform a more powerful swimmer with a poor stroke. A tennis player who can generate racket-head speed through kinetic chain rotation will out-serve one who relies purely on arm strength. The physics of sport reward precision of movement, and precision is a skill that must be taught.',
    ],
  },
  {
    id: 'economics',
    label: 'Economics',
    emoji: '💹',
    paragraphs: [
      'Comparative advantage, the principle that countries benefit from trading even when one country is better at producing everything, is one of the most counterintuitive and well-supported ideas in economics. It predicts that a country should specialise in what it is relatively better at producing and import the rest, even if it could produce the imported goods more efficiently. The gains from trade come from specialisation, not from absolute superiority.',
      'Inflation is a tax on savings and a subsidy to debtors. When prices rise, the real value of money held in cash or low-yield accounts falls. Borrowers repay their loans in money that is worth less than when they borrowed it. Central banks manage inflation through interest rates, expanding or contracting the money supply to keep price growth within targets that balance economic growth against the erosion of purchasing power.',
      'The gig economy has generated genuine flexibility for some workers and genuine precarity for others. Platform companies benefit from the productivity of their contractors without the obligations owed to employees: benefits, unemployment insurance, minimum hours, or protection from arbitrary termination. The regulatory frameworks designed to protect workers were built for a model of employment that the gig economy deliberately evades.',
    ],
  },
  {
    id: 'culture',
    label: 'Culture',
    emoji: '🎭',
    paragraphs: [
      'Culture is not a fixed thing that a group inherits but a set of practices, beliefs, and values that are continuously created and recreated through interaction. Cultures change in contact with other cultures, through internal disagreement and negotiation, and through the accumulated choices of millions of individuals. What feels like timeless tradition is often an invention of the recent past, given the weight of history through selective memory.',
      'Humour is among the most culturally specific forms of human expression. What is funny in one language rarely translates to another because jokes rely on shared assumptions, wordplay, and timing that are embedded in specific linguistic and cultural contexts. And yet the capacity for humour itself is universal. Every human culture has laughter, satire, and the ability to find relief from suffering through shared absurdity.',
      'The concept of childhood as a protected, extended period of play and learning is historically recent and still not universal. For most of human history, children were incorporated into productive labour as soon as they were physically capable, around seven or eight years old. The modern notion of childhood as a special phase requiring nurture, education, and protection from adult concerns emerged gradually in the nineteenth and twentieth centuries.',
    ],
  },
  {
    id: 'productivity',
    label: 'Productivity',
    emoji: '⚡',
    paragraphs: [
      'The most important productivity insight is that attention, not time, is the scarce resource. You can have eight hours free and produce nothing if your attention is fragmented by notifications, anxiety, or unclear priorities. You can also produce a week\'s worth of meaningful work in three focused hours. The fundamental practice is protecting blocks of uninterrupted attention for work that requires depth, and ruthlessly eliminating everything that does not deserve it.',
      'To-do lists are almost universally used and almost universally ineffective on their own. The problem is that a list of tasks does not tell you which task to do now, when to do it, how long it will take, or what to do when a task turns out to be more complex than expected. A calendar, which forces tasks into specific time blocks and confronts you with the reality of finite hours, is a more honest planning tool.',
      'The hardest part of any creative or intellectual project is starting. Once you have a draft, a prototype, or even a rough outline, revision is much easier than creation from nothing. The perfectionist\'s trap is delaying the start until conditions are perfect, which means never starting. The most effective creative workers develop a tolerance for low-quality beginnings and trust in the revision process to shape the material into something worthwhile.',
    ],
  },
  {
    id: 'animals',
    label: 'Animals',
    emoji: '🐘',
    paragraphs: [
      'Elephants demonstrate grief behaviours that are unmistakable even to untrained observers. They return to the bones of deceased herd members and touch them gently with their trunks. They stand vigil over dying individuals and remain near the body for hours or days after death. Whether this constitutes grief in the same subjective sense that humans experience it is unknowable, but the behaviour is functionally identical to mourning and appears to serve social and emotional purposes.',
      'Octopuses are among the most cognitively sophisticated animals relative to their evolutionary distance from humans. They have distributed nervous systems, with most of their neurons in their arms rather than their central brain. They can solve puzzles, use tools, escape from enclosures, and recognise individual humans. Their intelligence evolved entirely independently from vertebrate intelligence, suggesting that complex cognition can arise through radically different anatomical pathways.',
      'Migratory birds navigate using a combination of the sun\'s position, star patterns, magnetic field detection, and remembered landmarks. Experiments with altered magnetic fields, obscured skies, and displaced release points reveal a sophisticated and redundant navigation system that can compensate for many types of interference. Young birds learn some of these cues from experience, but the basic framework is innate, encoded in their nervous systems before their first migration.',
    ],
  },
];

// ─── Custom Topic Generator ────────────────────────────────────────────────────

// Sentence templates that work with any topic
const INTRO_TEMPLATES = [
  'The study of [TOPIC] has fascinated thinkers, researchers, and practitioners for generations.',
  'Few subjects touch as many areas of everyday life as [TOPIC], yet most people rarely stop to examine it carefully.',
  '[TOPIC] sits at the intersection of human curiosity and practical necessity, drawing attention from fields as different as science and philosophy.',
  'Understanding [TOPIC] deeply requires moving past the surface-level facts that most introductions offer.',
  'What most people know about [TOPIC] is the simplified version, the one that fits comfortably into conversation but leaves out the interesting complexity.',
];

const BODY_TEMPLATES = [
  'The historical development of [TOPIC] reveals how dramatically human understanding can shift within a few generations. Ideas that once seemed settled have been overturned, and approaches that seemed radical have become mainstream.',
  'Experts in [TOPIC] often disagree on foundational questions that outsiders assume are long resolved. This is not a failure of the field but evidence of its vitality. Active disagreement drives the questions that generate new knowledge.',
  'The practical applications of [TOPIC] extend further than most people expect. What begins as abstract inquiry has a way of producing tools, techniques, and insights that transform how we live and work.',
  'Learning about [TOPIC] changes how you see related subjects. Once you understand its core principles, patterns start appearing in places where you never noticed them before. This transfer of understanding is one of the most rewarding aspects of genuine study.',
  'The most common misconceptions about [TOPIC] tend to cluster around a few persistent myths. These myths persist not because people are careless but because the true picture is counterintuitive and requires more sustained attention to grasp.',
];

const CLOSE_TEMPLATES = [
  'Engaging seriously with [TOPIC] rewards patience. The interesting questions are rarely answered quickly, and the most valuable insights come only after the initial layer of information has been absorbed and examined from multiple angles.',
  'There has never been a better time to explore [TOPIC]. The volume of accessible, high-quality information available means that anyone with curiosity and time can develop a genuinely sophisticated understanding without formal instruction.',
  'The people who contribute most to our understanding of [TOPIC] share a quality beyond intelligence or education: they are willing to change their minds when the evidence requires it. This intellectual honesty is harder than it sounds and rarer than it should be.',
];

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function inject(template: string, topic: string): string {
  // Capitalise first letter of topic for sentence starts
  const cap = topic.charAt(0).toUpperCase() + topic.slice(1);
  return template.replace(/\[TOPIC\]/g, cap);
}

/**
 * Generates a custom topic passage from the user's input.
 * Produces ~150 words of coherent, on-topic text without an AI API.
 */
export function generateCustomTopicText(topic: string): string {
  const intro = inject(pick(INTRO_TEMPLATES), topic);
  const body1 = inject(pick(BODY_TEMPLATES), topic);
  const body2 = inject(
    BODY_TEMPLATES.filter((t) => t !== body1)[
      Math.floor(Math.random() * (BODY_TEMPLATES.length - 1))
    ],
    topic
  );
  const close = inject(pick(CLOSE_TEMPLATES), topic);
  return [intro, body1, body2, close].join(' ');
}

/**
 * Returns a random paragraph for a given preset topic ID.
 * Falls back to custom generator if the topic ID is not in the preset list.
 */
export function getTopicText(topicId: string, customTopic?: string): string {
  const preset = PRESET_TOPICS.find((t) => t.id === topicId);
  if (preset) {
    return pick(preset.paragraphs);
  }
  return generateCustomTopicText(customTopic || topicId);
}
